server_py/flatgov/crs/urls.py
from django.urls import path
from crs.views import CSVDownloadView

urlpatterns = [
    path('csv-download/', CSVDownloadView.as_view(), name='csv-download'),
]

server_py/flatgov/flatgov/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='home/', permanent=False), name='index'),
    path('bills/', include('bills.urls')),
    path('', include('home.urls')),
    path('uscongress/debug/', include('uscongress.urls')),
    path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
    path('crs/', include('crs.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server_py/flatgov/home/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.views.decorators.cache import never_cache

from home import views
from home.propublica_api_views import GetPressStatementsAPIView

app_name = 'home'

urlpatterns = [
    # path('', views.index, name='index'),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path('home/', views.home_view, name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
]

api_urlpatterns = [
    path('home/bill-list/', never_cache(views.BillListAPIView.as_view()), name='bill-list'),
    path('home/bill-titles/<congressnumber>', never_cache(views.BillListTitleAPIView.as_view()), name='bill-titles'),
    path('home/bill-title/<bill>/', never_cache(views.GetBillTitleAPIView.as_view()), name='bill-title'),
    path('press-statements/<congress>/<bill_type>/<bill_number>/', never_cache(GetPressStatementsAPIView.as_view()),
         name='press-statements'),
]

urlpatterns += api_urlpatterns

server_py/flatgov/templates/CRSDownload.html
{% extends 'base.html' %}

{% block content %}
<style>
    strong {
        font-weight: bolder;
    }
</style>
<div class="d-flex justify-content-center">
    <div class=" my-5 container ml-4 mr-4">
        <article class="mx-3 px-5">
            <h3>Download CSR</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="submit" class="btn btn-primary">
            </form>
            {% if file %}
                <hr>
                {% if file.file %}
                    <h5>Click the below link to download CSV file.</h5>
                    <br>
                    <a href="{{ file.file.url }}">{{ file.file.url }}</a>,&nbsp;
                {% elif file.log %}
                    <h5>Failed</h5>
                    <br>
                    <p>{{ file.log }}</p>
                {% else %}
                    <h5>CSV file is being generated... Please reload the page after ~ 10 minutes...</h5>
                {% endif %}
            {% endif %}     
        </article>
    </div>    
</div>

{% endblock content %}

server_py/flatgov/templates/base.html
{% load static %}
{% load rest_framework %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <link rel="https://cdnjs.cloudflare.com/ajax/libs/jquery-typeahead/2.11.0/jquery.typeahead.min.css" crossorigin="anonymous" />

    <!-- font awesome -->
    <script src="https://use.fontawesome.com/4b14720de5.js"></script>
    <title>BillMap</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.bootstrap4.min.css' %}">
    <link href="{% static 'assets/fullcalendar/main.css' %}" rel='stylesheet' />
    <link href="{% static 'css/select.css' %}" rel='stylesheet' />
    <link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Public+Sans&display=swap');
    </style>
    {% block extra_css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<header>
    {% include 'navbar.html' %}
</header>

<body>
    <div class="">

        {% block content %}
        {% endblock %}

    </div>
    <footer>
        {% include 'footer.html' %}
    </footer>
    
    <!-- jQuery first, then Popper.js, then Bootstrap JS and typeahead -->
    <!-- Uses the full version of jQuery for ajax functions -->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper-1.16.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/typeahead.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'assets/moment/moment.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/fullcalendar/main.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/ColReorderWithResize.js' %}"></script>

    <script type="text/javascript" language="javascript" src="{% static 'js/dataTables.buttons.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/buttons.html5.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/buttons.print.min.js' %}"></script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>

server_py/flatgov/templates/footer.html
{% load static %}
{% load render_attrs %}

{% url '/home' as home_path %}
{% url '/about' as about_path %}
<div class="row d-sm-flex justify-content-center dark-blue-footer py-5">
    <div class="col-md-10 m-3">

        <div class="">
           <div class="d-md-flex justify-content-between">
               <div>
                <ul class="nav flex-row" style="color: wheat;">
                    <li class="nav-item mb-2">
                        <a class="link" title="documentation" href="/static/docs/index.html">Documentation</a>
                    </li>
                    <li class="nav-item mb-2">
                        <a class="link" href="/crs/csv-download/">Data Download</a>
                    </li>
                </ul>
               </div>
               <div class="d-flex align-items-center mt-3 m-sm-0">
                    {% app_version as app_version %}
                    <span class="mr-4 text-danger">
                        {{ app_version }}
                    </span>
               </div>
           </div>
        </div>
    </div>
</div>

server_py/flatgov/templates/navbar.html
{% load static %}
{% load rest_framework %}
{% load render_attrs %}

{% url '/home' as home_path %}
{% url '/about' as about_path %}
<div class="row d-flex justify-content-center dark-blue-navbar">
    <div class="col-md-10">

        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="/home"><img src="{% static '/images/billmap_logo.png' %}" style="height: 100px;" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="navbar-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'home:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="/about">About Us</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>